version: '2.3'
services:

  # -----------------------------------------------------------------------------------------------
  # PHP Container Tweaks
  # -----------------------------------------------------------------------------------------------
  php:
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  # -----------------------------------------------------------------------------------------------
  # Portainer Container Mgr
  # -----------------------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce
    hostname:  portainer
    restart: always
    ports:
    - "${LOCAL_LISTEN_ADDR}${HOST_PORT_PORTAINER:-9000}:9000"
    - "${LOCAL_LISTEN_ADDR}${HOST_PORT_PORTAINER_AGENT:-8000}:8000"
    networks:
      app_net:
        ipv4_address: 172.16.238.230
    volumes:
    - devilbox-portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock

  # -----------------------------------------------------------------------------------------------
  # ELK Stack
  # -----------------------------------------------------------------------------------------------
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_SERVER:-6.6.1}
    hostname: elastic
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_ELK_ELASTIC:-9200}:9200"
    networks:
      app_net:
        ipv4_address: 172.16.238.240
    environment:
      - TZ=${TIMEZONE:-UTC}
      - discovery.type=single-node
    volumes:
      - devilbox-elastic:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELK_SERVER:-6.6.1}
    hostname: logstash
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_ELK_LOGSTASH:-9600}:9600"
    networks:
      app_net:
        ipv4_address: 172.16.238.241
    environment:
      - TZ=${TIMEZONE:-UTC}
      - LOG_LEVEL=info
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=9600
      - CONFIG_RELOAD_AUTOMATIC=true
      - CONFIG_RELOAD_INTERVAL=300
      - DB_HOST=DATABASE-SERVER
    volumes:
      - devilbox-logstash:/var/lib/logstash
    depends_on:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELK_SERVER:-6.6.1}
    hostname: kibana
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_ELK_KIBANA:-5601}:5601"
    networks:
      app_net:
        ipv4_address: 172.16.238.242
    environment:
      - TZ=${TIMEZONE:-UTC}
      - ELASTICSEARCH_URL=http://elastic:9200
    depends_on:
      - elastic
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper:/bitnami'
    networks:
      app_net:
        ipv4_address: 172.16.238.243

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - type: volume
        source: kafka
        target: /bitnami/kafka
      - type: bind
        source: ./cfg/kafka-latest/conf
        target: /opt/bitnami/kafka/conf
    networks:
      app_net:
        ipv4_address: 172.16.238.244
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
volumes:
  devilbox-php:
  devilbox-portainer:
  devilbox-elastic:
  devilbox-logstash:
  zookeeper:
  kafka:


